import type { NextPage } from 'next';
import Head from 'next/head';
import { useSession } from 'next-auth/react';
import styles from '../styles/login.module.css';
import Login from '../components/Login';
import Register from '../components/Register';

function Home() {
  const { status } = useSession();

  return (
    <div>
      <Head>
        <title>Project Manager</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.mainContainerRegisterLogin}>
        {
          (status === 'loading') ? <h1 className={styles.loadingRegisterLogin}>Loading...</h1> : (
            <div className={styles.containerRegisterLogin}>
              <div className={styles.logoRegisterLogin}>
                <p>Mape</p>
              </div>
              <div className={styles.registerLogin}>
                <Register />
                <Login />
              </div>
            </div>
          )
        }
      </main>
    </div>
  );
}

export default Home as NextPage;
