import type { NextPage } from 'next';
import Head from 'next/head';
import Login from '../components/Login';
import Register from '../components/Register';
import styles from '../styles/Home.module.css';

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Project Manager</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Register />
        <Login />
      </main>
    </div>
  );
};

export default Home;
